apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client # The Deployment selects Pods with this label
  template:
    metadata:
      labels:
        app: client # This label is added to every Pod created by this Deployment
    spec:
      containers:
        - name: client
          image: sherryz707/client:latest
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000