apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus # The Deployment selects Pods with this label
  template:
    metadata:
      labels:
        app: event-bus # This label is added to every Pod created by this Deployment
    spec:
      containers:
        - name: event-bus
          image: sherryz707/event-bus:latest
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector:
    app: event-bus
  type: ClusterIP
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005