apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation # The Deployment selects Pods with this label
  template:
    metadata:
      labels:
        app: moderation # This label is added to every Pod created by this Deployment
    spec:
      containers:
        - name: moderation
          image: sherryz707/moderation:latest
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation
  type: ClusterIP
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003