apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts # The Deployment selects Pods with this label
  template:
    metadata:
      labels:
        app: posts # This label is added to every Pod created by this Deployment
    spec:
      containers:
        - name: posts
          image: sherryz707/posts:latest
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  type: ClusterIP
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000